all:
	hipcc rocblasMatrixMul_d.cpp -o rocblasMatrixMul_d -I/opt/rocm/rocblas/include/ -L/opt/rocm/rocblas/lib/ -lrocblas
	hipcc rocblasMatrixMul_f.cpp -o rocblasMatrixMul_f -I/opt/rocm/rocblas/include/ -L/opt/rocm/rocblas/lib/ -lrocblas
